services:
  jsg-llm-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jsg-llm-api
    network_mode: "host"
    environment:
      - PORT=8080
      - VERBOSE=true
    restart: unless-stopped

